apiVersion: apps/v1
kind: Deployment
metadata:
  name: blender-deployment
  labels:
    app: blender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blender
  template:
    metadata:
      labels:
        app: blender
    spec:
      containers:
        - name: blender
          image: mohamedanter845/blender-flask:latest                         
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080                     
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
          volumeMounts:
            - name: blender-storage
              mountPath: /renders
      volumes:
        - name: blender-storage
          persistentVolumeClaim:
            claimName: blender-output-pvc

