apiVersion: v1
kind: Service
metadata:
  name: blender-service
spec:
  selector:
    app: blender
  ports:
    - protocol: TCP
      port: 8080        
      targetPort: 8080  
      nodePort: 30080   
  type: NodePort

